import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className="flex flex-col h-screen">
        <header className=" bg-blue-500 p-4 flex gap-4 ">
          <div className=" text-white">
            <Link href={"/data"}>单机数据管理</Link>
          </div>
          <div className=" text-white">
            <Link href={"/setting"}>系统设置</Link>
          </div>
        </header>
        <main className=" flex-1">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </main>
      </body>
    </html>
  );
}
