import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import Link from "next/link";
import RedisIcon from "./icons/redisIcon";
import { Button } from "antd";
import GitHubIcon from "./icons/GithubIcon";
import HomeIcon from "./icons/HomeIcon";
import DataAnalyzeIcon from "./icons/DataAnalyzeIcon";
import SetIcon from "./icons/SetIcon";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className="flex h-screen">
        <div className=" h-full w-16 p-2 bg-blue-800 flex flex-col items-center ">
          <div className=" w-full bg-white rounded flex items-center justify-center py-1">
            <RedisIcon></RedisIcon>
          </div>

          <div className=" flex-1 flex flex-col gap-2 mt-6 ">
            <div className=" text-white hover:bg-blue-900 p-3 ">
              <Link href={"/data"}>
                <HomeIcon className=" text-2xl"></HomeIcon>
              </Link>
            </div>
            <div className=" text-white hover:bg-blue-900 p-3">
              <Link href={"/setting"}>
                <DataAnalyzeIcon className=" text-2xl"></DataAnalyzeIcon>
              </Link>
            </div>
            <div className=" text-white hover:bg-blue-900 p-3">
              <Link href={"/setting"}>
                <SetIcon className=" text-2xl"></SetIcon>
              </Link>
            </div>
          </div>

          <a href="https://github.com/erhulee">
            <GitHubIcon></GitHubIcon>
          </a>
        </div>
        <main className=" flex-1">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </main>
      </body>
    </html>
  );
}
