import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import Link from "next/link";
import RedisIcon from "./icons/RedisIcon";
import GitHubIcon from "./icons/GithubIcon";
import HomeIcon from "./icons/HomeIcon";
import DataAnalyzeIcon from "./icons/DataAnalyzeIcon";
import SetIcon from "./icons/SetIcon";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className="flex h-screen">
        <div className=" h-full w-16 p-2 pb-4  flex flex-col items-center bg-primary-900  ">
          <div className=" w-8 h-8 bg-white rounded-full flex items-center justify-center py-1">
            <RedisIcon></RedisIcon>
          </div>

          <div className=" flex-1 flex flex-col gap-2 mt-6  ">
            <div className=" text-white hover:bg-primary-700 p-3 rounded ">
              <Link href={"/data"}>
                <HomeIcon className=" text-2xl"></HomeIcon>
              </Link>
            </div>
            <div className="text-white hover:bg-primary-700 p-3 rounded">
              <Link href={"/setting"}>
                <DataAnalyzeIcon className=" text-2xl"></DataAnalyzeIcon>
              </Link>
            </div>
            <div className="text-white hover:bg-primary-700 p-3  rounded">
              <Link href={"/analyze"}>
                <SetIcon className=" text-2xl"></SetIcon>
              </Link>
            </div>
          </div>

          <a href="https://github.com/erhulee">
            <GitHubIcon></GitHubIcon>
          </a>
        </div>
        <main className=" flex-1">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </main>
      </body>
    </html>
  );
}
